name: richhabit
description: Rich Habit - Second Youngthly Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.4.2
  provider: ^4.3.2
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.18.0
  table_calendar: ^2.2.3
  flutter_group_sliver: ^0.0.2
  fluttertoast: ^7.0.2
  fl_chart: ^0.11.0
  flutter_local_notifications: ^1.4.4+2
  configurable_expansion_tile: 
    git:
      url: https://github.com/bkRyusim/configurable_expansion_tile.git
      ref: master
  shared_preferences: ^0.5.8
  google_fonts: ^1.1.0
  url_launcher: ^5.5.0
  scroll_to_index: ^1.0.6
  flutter_keyboard_visibility: ^3.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icon/
    - assets/markdowns/
    - assets/guide/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_native_splash:
  image: assets/images/Splash_Logo.png
  color: "585A79"
